var tongdata = [
    {   
        id: 1,
        name:'Life Size Bronze Golfer Statue',
        title: 'Bronze Golfer Statue',
        num: 'FGTS-001',
        Material: 'bronze',
        type: 'bronze Golfer other sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'This is a bronze golfer statue. The sculpture fixes the moment when a golfer swings his golf club, making time seem to come to a standstill at that moment. Every line and angle is carefully designed, and the player’s body twists to form a tense posture, reflecting the perfect combination of strength and elegance.',
            'Bronze statues of golfers are widely used to decorate and beautify the environment in golf clubs, tournament venues, and other places. They can be placed at the entrance of the stadium, club hall, or game memorial area, becoming a beautiful scenery.',
            'Bronze golf player statues are increasingly appearing in public spaces in cities, such as parks, squares, and even commercial centers. They have become a part of the urban landscape, enriching the cultural life of citizens and providing tourists with more opportunities to learn about local characteristics.',
            'We are committed to providing you with unique sculpture customization services. Whether you are seeking an artwork that showcases your personal taste or hoping to add iconic landscapes to your business or public space, our professional team can carefully design and produce sculptures that meet your specific needs and vision.'
        ],
        img: [
            'img/bronze/golf-player1.jpg',
            'img/bronze/golf-player2.jpg',
            'img/bronze/golf-player3.jpg',
            'img/bronze/golf-player4.jpg',
        ]
    },
    {   
        id:2,
        name:'Bronze Cherub Angel Garden Statues',
        title: 'Bronze Cherub Angel Statue',
        num: 'XTSD-001',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze angel garden sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'This is a bronze cherub angel garden statues. The scene of three cute little angels playing music on the shelf. The little angel standing at the top of the shelf is a very special character. He holds the violin, which is supported on the ground, pressing the strings with one hand and pulling the violin with the other. Two other little angels sat on the shelf, playing the flute and the trumpet respectively. They work together to create wonderful music. This scene is full of joy and vitality, while also bringing peace and beauty to people.',
            'In Western art and religious culture, the Cherub is often depicted as a winged child or baby, symbolizing purity, innocence, and a presence close to God. In Christian tradition, little angels are often seen as messengers of heaven, flying around God, carrying out tasks of praise and service.',
            'This cherub angel garden statues can be used to decorate outdoor spaces, such as the entrance to a garden or the center of a courtyard, as a welcome to guests and a foreshadowing of life celebrations. Internally, it can be placed in the living room or dining room to add a festive atmosphere to family gatherings and celebrations.',
            'We are committed to providing you with unique sculpture customization services. Whether you are seeking an artwork that showcases your personal taste or hoping to add iconic landscapes to your business or public space, our professional team can carefully design and produce sculptures that meet your specific needs and vision.'
        ],
        img: [
            'img/bronze/angel-garden.jpg',
            'img/bronze/angel-garden1.jpg',
            'img/bronze/angel-garden2.jpg',
            'img/bronze/angel-garden3.jpg',
        ]
    },
    {   
        id: 3,
        name:'Bronze Life Size Bear Sculpture Fighting With Eagle',
        title: 'Bronze Bear Eagle Statue',
        num: 'QIXY-001',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze bear Eagle sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'Bronze Life Size Bear Sculpture showcases the scene of bears and eagles fighting for food in nature with its unique concept and vivid expression. Bears, as powerful animals on land, occupy a place in this survival struggle with their majestic physique and brave personality. The eagle, on the other hand, has become the dominant figure in the sky with its agile posture and keen insight. The two engaged in a fierce battle over food.',
            'In this work, the sculptor vividly portrays the movements and expressions of bears and eagles in their struggle for survival. The bear stood with its hind legs, its two front paws tightly grasping the fish’s tail, opening its mouth to reveal its fangs, attempting to repel the eagle. This action not only demonstrates the strength of the bear, but also demonstrates its determination and bravery in facing challenges. The eagle, with its agile body and claws, grasps the fish’s head and fearlessly confronts the bear. This detail not only demonstrates the agility of the eagle, but also reflects its courage and wisdom in facing strong enemies.',
            'Bronze Life Size Bear Sculpture Fighting With Eagle is a bronze sculpture cast using the lost wax casting method, which can be used to decorate and beautify the environment, adding cultural atmosphere. This work can also be used as a part of tourist attractions to attract tourists and enhance the cultural connotation of the scenic area.',
            'At the same time, it can also be given as a gift to family and friends or as a business gift, showcasing the giver’s taste and intentions. In summary, the Bronze Life Size Bear Sculpture Fighting With Eagle has become an important medium for people to appreciate, think, and express emotions in their daily lives due to its unique artistic charm and rich cultural connotations.'
        ],
        img: [
            'img/bronze/bear1.jpg',
            'img/bronze/bear2.jpg',
            'img/bronze/bear3.jpg',
            'img/bronze/bear4.jpg',
        ]
    },
    {   
        id: 4,
        name:'Bronze ballet dancer figurines',
        title: 'Bronze ballet dancer Statue',
        num: 'QIXY-201',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze ballet dancer sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'Bronze ballet dancer figures is an art piece with ballet dancers as its theme. The image of ballet dancers is portrayed as elegant and powerful. Her body lines are smooth and her posture is elegant, showcasing the unique softness and strength of ballet dancers. Her movements and expressions convey her love for dance and her persistent pursuit of art. In this sculpture, the ballet dancer is wearing a ballet skirt, standing on tiptoe on one leg, with the other leg extending backwards into the sky, arms open, and head tilted upwards. The dancer’s posture is graceful, showcasing high difficulty movements.',
            'The bronze material endows this sculpture with an ancient and mysterious atmosphere. The texture and color of bronze contrast sharply with the image of ballet dancers, while also highlighting the texture and three-dimensional sense of sculpture. The use of bronze not only showcases the craftsmanship of sculptors, but also makes the entire work more stable and durable.',
            'This sculpture is usually placed in a dance academy, theater, or dance performance venue, and the surrounding environment is filled with a dance atmosphere. The existence of sculptures adds an artistic atmosphere to these places, as if ballet dancers are performing live. The combination of environmental background and sculpture makes people more aware of the charm of dance and the artistic achievements of ballet dancers.',
            'We are committed to providing you with unique sculpture customization services. Whether you are seeking an artwork that showcases your personal taste or hoping to add iconic landscapes to your business or public space, our professional team can carefully design and produce sculptures that meet your specific needs and vision.'
        ],
        img: [
            'img/bronze/dancer1.jpg',
            'img/bronze/dancer2.jpg',
            'img/bronze/dancer3.jpg',
            'img/bronze/dancer4.jpg',
        ]
    },
    {   
        id: 5,
        name:'Bronze Girl Reading Sculpture Garden Statue',
        title: 'Bronze Girl Statue',
        num: 'QIXY-261',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze Girl Reading sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'The Bronze Girl Reading Sculpture is an artwork with the theme of a little girl. In this sculpture, a little girl sits on Earth, holding a book in one hand and a homework book in the other. She stared intently at the homework book in her hand, demonstrating her love for learning and thirst for knowledge.',
            'The combination of bronze and green in this sculpture makes it look more retro. Bronze symbolizes history and tradition, while green represents nature and vitality. This combination gives the sculpture a unique visual effect in terms of color, while also highlighting the little girl’s pursuit of knowledge and love for nature.',
            'This sculpture is usually placed in public places such as parks, squares, or commercial areas, adding an artistic touch to these places. The combination of sculpture and environmental layout makes the entire space more harmonious and beautiful. It has become a part of public art, providing people with a space to appreciate and experience art.',
            'Bronze little girl sculpture is also a way of cultural inheritance. It conveys the importance of knowledge, education, and social values through the image of a little girl and symbols of learning. This kind of inheritance helps people understand and respect history and culture, promoting the inheritance and development of culture.'
        ],
        img: [
            'img/bronze/girlonglobe1.jpg',
            'img/bronze/girlonglobe2.jpg',
            'img/bronze/girlonglobe3.jpg',
            'img/bronze/girlonglobe4.jpg',
        ]
    },
    {   
        id: 6,
        name:'Animal Garden Sculpture Bronze Doe and Fawn Statue',
        title: 'Bronze Animal Doe Statue',
        num: 'QIXY-041',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze Animal Doe sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'The bronze sculpture of mother and child deer vividly reproduces the scene of warm interaction between mother deer and young deer with its exquisite craftsmanship and realistic shape. The mother deer turned around and gently comforted the little deer with her mouth, her eyes showing endless tenderness and love. ',
            'The little deer snuggled under the mother deer’s body, ready to enjoy the warm moment of breastfeeding. The sculptural lines are simple and vivid, making people feel as if they can feel the temperature and breath between them.',
            'The bronze sculpture of mother and son deer is a hymn to family and life in nature. The mother deer symbolizes maternal love and care, and its turn to soothe and the dependence of the young deer reminds people of the greatness of maternal love and the warmth of home in human society. The deer represents rebirth and hope, and its existence gives people reverence for life and expectations for the future.',
            'Bronze mother and son deer sculptures can be used as public art works, placed in open spaces such as parks and squares for people to appreciate and reflect on. They can also be used as private collections to decorate home environments and add cultural atmosphere. In the commercial field, bronze mother and son deer sculptures can also serve as symbols of a company or brand, conveying the company’s respect for nature and family, and enhancing the company’s social responsibility image.'
        ],
        img: [
            'img/bronze/doe1.jpg',
            'img/bronze/doe2.jpg',
            'img/bronze/doe3.jpg',
            'img/bronze/doe4.jpg',
        ]
    },
    {   
        id: 7,
        name:'Life Size Bronze Paired Elephant Statue at Entrance',
        title: 'Bronze Elephant Statue',
        num: 'QIXY-022',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze Animal Elephant sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'This is a thailand elephant statue.  This elephant sculpture is made of bronze material, with a small and delicate shape, suitable for placement at store entrances, courtyard entrances, and other places. The posture of the little elephant standing is steady and elegant, with its four hooves firmly stepping on the base.',
            'The back is covered with a blanket with exquisite patterns, which use traditional Thai patterns and auspicious decorations. The little elephant has a gentle and friendly expression, with round and lively eyes，and a smile face, it looks very realistic.',
            'Elephant sculptures carry profound religious beliefs. Elephants are considered sacred animals, especially in Buddhism where they are the mount of Buddha, symbolizing the solemnity and sanctity of Buddhism. According to legend, when Buddha was born, his mother dreamed of a white elephant in her arms, so the elephant was regarded as a symbol of auspiciousness and purity.',
            'Elephants also represent strength, wisdom, and compassion, which are extremely important qualities in Buddhist doctrine. In temples and religious sites, Elephant Sculptures are often used for decoration and worship, not only adding a solemn atmosphere, but also embodying the devout faith of believers in Buddhism and their prayers for a better life.'
        ],
        img: [
            'img/bronze/elephant-1.jpg',
            'img/bronze/elephant-2.jpg',
            'img/bronze/elephant-3.jpg',
            'img/bronze/elephant-4.jpg',
        ]
    },
    {   
        id: 8,
        name:'Outdoor Bronze Woman Water Fountain',
        title: 'Bronze Fountain Statue',
        num: 'QIXY-022',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze Woman Fountain sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'The Bronze Woman Water Fountain is an artistic fountain sculpture with a female theme. In these sculptures, the women stand gracefully, accompanied by flowing water to create a beautiful scenery. These women elegantly hold water jars, gently hold water droplets, or dance gracefully, interweaving with the water flow of the fountain, together creating a moving scene.',
            'The water flow design of the bronze woman water fountain cleverly combines elements of motion and stillness. The water flows out from the water jar in the woman’s hand, the water droplets in her palm, or the dancing skirt hem, forming a layered water curtain. These water currents, whether light, turbulent, or slow, add a vivid atmosphere to the entire sculpture. Meanwhile, the flow of water also symbolizes the vitality of life and the ever-changing beauty.',
            'Bronze woman water fountain is a beautiful and moving artwork. It showcases a breathtaking beauty through the beautiful figure of a woman, clever water flow design, and the use of bronze material. This sculpture is not only a work of art, but also a tribute to women, nature, and the power of life. It allows us to appreciate the beautiful scenery while also feeling the power of art and the depth of culture.',
            'We are committed to providing you with unique sculpture customization services. Whether you are seeking an artwork that showcases your personal taste or hoping to add iconic landscapes to your business or public space, our professional team can carefully design and produce sculptures that meet your specific needs and vision.'
        ],
        img: [
            'img/bronze/woman-1.jpg',
            'img/bronze/woman-2.jpg',
            'img/bronze/woman-3.jpg',
            'img/bronze/woman-4.jpg',
        ]
    },
    {   
        id: 9,
        name:'Life size bronze horse sculpture',
        title: 'Bronze horse Statue',
        num: 'FGTS-022',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze horse sculpture',
        price: 'USD 890-3860 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'The life size bronze horse sculpture consists of three horses, each with a different posture, yet each showcasing the power and beauty of the horse. One of the horses jumped up, tilted its head back, opened its mouth and hissed, as if calling out to its distant companions. Its mane and tail sway with the wind, and its muscle lines are delicately portrayed, showcasing the strength and vitality of a horse.',
            ' Its mane and tail sway with the wind, and its muscle lines are delicately portrayed, showcasing the strength and vitality of a horse. The other horse jumped up, its head lowered, as if focused on observing the ground. Its posture was both elegant and agile. The third horse is presented in a running posture, with its limbs vigorously running forward, demonstrating the speed and passion of the horse. The bases under their feet are like rolling waves, adding a touch of dynamism and vividness.',
            'The horse, as a symbol of freedom, strength, and beauty, is known as the “soul of the earth”. In this work, the image of a horse is not only a representative of an animal, but also a symbol of spirit. Their free running symbolizes humanity’s longing for freedom and pursuit of power, while their unity and cooperation represent humanity’s longing for a harmonious society. This work conveys a positive and courageous spirit through the image of a horse, inspiring people to face challenges and pursue excellence.',
            'The use of bronze horse sculptures is very extensive. As a public art piece, it is suitable for placement in public places such as parks, squares, museums, etc. It not only beautifies the environment, but also stimulates people’s yearning for freedom, power, and beauty. In the private sphere, this sculpture can serve as a symbol of enterprise or family, showcasing its image of freedom and power. In addition, this sculpture can also be used as a souvenir or gift to convey profound emotions and good wishes.'
        ],
        img: [
            'img/bronze/horse-1.jpg',
            'img/bronze/horse-2.jpg',
            'img/bronze/horse-3.jpg',
            'img/bronze/horse-4.jpg',
        ]
    },
    {   
        id: 10,
        name:'Abstract bronze sculpture for sale',
        title: 'Bronze Abstract Statue',
        num: 'CXDS-001',
        Material: 'Bronze/ Brass / Copper',
        type: 'bronze Abstract other sculpture',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'Bronze abstract sculptures depict a couple embracing each other, showcasing the profound expression of human emotions through abstract lines and forms. Embracing, as the most basic way of human emotional communication, has been endowed with profound symbolic significance. The lines in the sculpture are smooth and simple, as if telling the connection and bond of various emotions such as love, family, and friendship.',
            'These lines are not only a visual enjoyment, but also an exploration of form and structure. Sculptors create a unique visual effect by arranging and combining lines, giving sculptures a sense of hierarchy and dimensionality.',
            'Abstract sculpture is an important component of modern art, which originated in early 20th century Europe and developed with the rise of artistic movements such as abstract expressionism and constructivism. Abstract sculpture emphasizes the importance of form and structure, as well as how they exist independently of the concrete world. This art form not only challenges traditional artistic concepts, but also provides artists with infinite creative space.',
            'Bronze abstract sculptures can be placed in public spaces such as parks, squares, or commercial areas, adding an artistic touch to the city. They can also be placed in private spaces such as galleries, art galleries, or family interiors, adding a unique artistic atmosphere to the space. In addition, bronze abstract sculptures can also serve as a part of sculpture parks or gardens, providing people with a place to appreciate and experience abstract art.'
        ],
        img: [
            'img/bronze/abstract-1.jpg',
            'img/bronze/abstract-2.jpg',
            'img/bronze/abstract-3.jpg',
            'img/bronze/abstract-4.jpg',
        ]
    },
    {   
        id: 11,
        name:'Fiberglass Large seated kuan yin statue',
        title: 'Fiberglass kuan yin Statue',
        num: 'CXDS-001',
        Material: 'Fiberglass',
        type: 'Fiberglass kuan yin statue sculpture',
        price: 'USD 810-3990 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'This fiberglass Large seated kuan yin statue showcases the compassionate image of Guanyin. Guanyin sat on the lotus base, holding a willow branch in one hand and a jade clean bottle in the other, with a kind face, giving people a feeling of peace and tranquility.',
            'This design showcases the compassion and wisdom of Guanyin, giving people a sense of tranquility and nobility. The golden appearance gives people a noble and elegant feeling, adding artistic value to sculpture. Sculptures made of fiberglass are more durable and aesthetically pleasing in outdoor environments.',
            'In Buddhist culture, Guanyin symbolizes compassion, wisdom, and redemption. This fiberglass Guanyin sculpture symbolizes Guanyin’s compassion and wisdom through its unique shape and golden main color scheme. It adds an artistic atmosphere to the space, allowing people to feel the beauty and blessings brought by Guanyin.',
            'We can provide customized services, and according to customer requirements, we can perform surface treatments such as spray painting and painting to make the sculpture present the effect you want. This enables sculpture to better meet the needs of different occasions and environments, adding a unique artistic charm to the space.'
        ],
        img: [
            'img/bronze/guanyin-1.jpg',
            'img/bronze/guanyin-2.jpg',
            'img/bronze/guanyin-3.jpg',
            'img/bronze/guanyin-4.jpg',
        ]
    },
    {   
        id: 12,
        name:'Customize Life Sized Fiberglass Super Mario statue',
        title: 'Fiberglass Super Mario Statue',
        num: 'KWSD-055',
        Material: 'fiberglass/resin/stainless steel',
        type: 'Fiberglass mario statue sculpture',
        size: 'Life size or as requested',
        price: 'USD 870-3990 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: ' Cartoon Statue, Fiberglass Sculpture',
        introduction: [
            'This Mario fiberglass statue, meticulously crafted by a master artisan, brings every detail to life.',
            'Mario’s iconic red overalls and blue work clothes areantly colored, as if he has just experienced an adventure in the Mushroom Kingdom.',
            'The statue is made of high-quality fiberglass, which is durable, waterproof, and sun. Whether placed in an indoor study, game room, or outdoor courtyard, garden, it can perfectly blend into the environment and become a unique scenic line. It is only a decoration but also a precious collection of childhood game memories.',
            'We have made a lot of the popular statues. Please contact us for more details, i would like to share you more of our statues pictures for you choose from.'
        ],
        img: [
            'img/bronze/mario-1.jpg',
            'img/bronze/mario-2.jpg',
            'img/bronze/mario-3.jpg',
            'img/bronze/mario-4.jpg',
        ]
    },
    {   
        id: 13,
        name:'Bronze fishing sculpture',
        title: 'Bronze fishing Statue',
        num: 'YSMD-066',
        Material: 'Bronze/ Brass/ Copper',
        type: 'Bronze fishing sculpture',
        size: 'Life size or as requested',
        price: 'USD 830-3700 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: 'period: 30-45days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: 'Bronze Sculpture, Sport Statue',
        introduction: [
            'This bronze sculpture of a child fishing depicts a little boy wearing a domed hat, bending over to admire his fresh catch.',
            'He is sitting on a flat base still holding his bronze fishing rod and bronze fish.It is suitable for placement next to the park pond.',
            'This sculpture is made of bronze, using the lost wax method to ensure the highest quality and excellent detail. The hand-applied bronze patina makes the and his fishing rod even more perfect.',
            'Xintuo Sculpture focuses on creating high-quality figure sculpture projects. Our figure sculpture cover a variety of styles and sizes. Each work embodies the hard work and exquisite skills of craftsmen.'
        ],
        img: [
            'img/bronze/fishing-1.jpg',
            'img/bronze/fishing-2.jpg',
            'img/bronze/fishing-3.jpg',
            'img/bronze/fishing-4.jpg',
            'img/bronze/fishing-5.jpg',
        ]
    },
    {   
        id: 14,
        name:'Outdoor decoration life-size bull statue',
        title: 'Bronze bull Statue',
        num: 'BCDS-69',
        Material: 'Bronze/ Brass/ Copper',
        type: 'fiberglass bull sculpture',
        size: 'Life size or as requested',
        price: 'USD 800-3900 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'strong wooden cases or iron frame boxes.',
        Categories: 'Fiberglass bull statue, Fiberglass Sculpture',
        introduction: [
            "The bull de wall street is crafted with precision and artistic style, and the intricate details in the sculpture highlight the artist’s dedication to realism, making it engaging work of art.",
            "The bull, often a symbol of determination and strength, is presented in a way that emphasizes its robustness and command.",
            "The texture and contours the sculpture bring the bull to life, showcasing the interplay of light and shadow, and enhancing its three-dimensional quality.",
            "This bull sculpture is more than just a decorative; it is a symbol of vitality and endurance. It would make an outstanding addition to any collection, whether displayed in a home, office, or public space."
        ],
        img: [
            'img/bronze/fiberglass-bull-1.jpg',
            'img/bronze/fiberglass-bull-2.jpg',
            'img/bronze/fiberglass-bull-3.jpg',
            'img/bronze/fiberglass-bull-4.jpg',
        ]
    },
    {   
        id: 15,
        name:'Outdoor decoration garden Buddha sculpture',
        title: 'marble Buddha Statue',
        num: 'XTSD-222',
        Material: 'Natural marble',
        type: 'Marble Buddha Statue sculpture',
        size: 'Life size or as requested',
        price: 'USD 850-3960 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: ' Marble Buddha Statue, Marble Carving Sculpture',
        introduction: [
            "This outdoor garden Buddha sculpture is exquisitely crafted, embodying tranquility and spiritual depthThe statue’s intricate details highlight the artisan’s skill, from the delicate facial features to the flowing robes that drape gracefully.",
            "The Buddha’s expression is calm and meditative, evoking a sense of peace and enlightenment. The simplicity of the background enhances the statue’s sacred presence, making it a perfect addition to any home or sacred space.",
            "This Buddha statue is not only a beautiful piece of art but also a symbol of tranquility and mindfulness, ideal for those seeking to create a serene and contemplative environment.",
            "This outdoor decoration buddha statue showcases a magnificent Buddha statue, exquisitely carved to depict the tranquility and wisdom of the Buddha."
        ],
        img: [
            'img/bronze/marble-Buddha-1.jpg',
            'img/bronze/marble-Buddha-2.jpg',
            'img/bronze/marble-Buddha-3.jpg',
            'img/bronze/marble-Buddha-4.jpg',
        ]
    },
    {   
        id: 16,
        name:'Life Size Marble Big Mermaid Garden Statue',
        title: 'marble Mermaid Statue',
        num: 'MRED-011',
        Material: 'Marble/Bronze/Brass',
        type: 'Marble Mermaid Statue sculpture',
        size: 'Life size or as requested',
        price: 'USD 810-3970 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: ' Marble Buddha Statue, Marble Carving Sculpture',
        introduction: [
            "This big mermaid statue uses high-quality marble to ensure the durability and beauty of the statue. Seated, standing or lying down, the statue is designed to show the mermaid sitting on a rock with her tail naturally lowered and holding a shell or other Marine element in her hands. The mermaid’s scales, hair and facial expressions have been carefully sculpted to look realistic.",
            "This Bronze mermaid sculpture is suitable for placing in gardens, courtyards, villas or art galleries, which can enhance the beauty of the garden or courtyard, adding the mystery and elegant atmosphere of the space. This life-size marble statue of the Great Mermaid is not only a work of art, but can also add a unique charm and cultural touch to your garden or courtyard.",
            "In addition to the aforementioned products, we offer a variety of other styles for you to choose from. Naturally, we also support customized images in any style and size.",
        ],
        img: [
            'img/bronze/marble-mermaid-1.jpg',
            'img/bronze/marble-mermaid-2.jpg',
            'img/bronze/marble-mermaid-3.jpg',
            'img/bronze/marble-mermaid-4.jpg',
        ]
    },
    {   
        id: 17,
        name:'musical dancing fountain',
        title: 'Metal fountain Statue',
        num: 'MRED-011',
        Material: 'Metal',
        type: 'Metal fountain sculpture',
        size: 'Life size or as requested',
        price: 'USD 690-3950 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: '',
        PackageOut: '',
        Categories: ' Fountain Construction',
        introduction: [
            "Music dancing fountain is a comprehensive performance art form that integrates music, dance, and fountain art. It creates a dual enjoyment of visual and auditory by combining water dance movements with musical rhythms.",
            "The main components of a music and dance fountain include a fountain system, which is the core part of the fountain and includes equipment such as water pumps, pipes, and nozzles. Music control system and lighting system, etc.",
            "The expression forms of music and dance fountains are diverse and can be customized according to different music and occasions. The water dance movements of fountains can be designed based on the rhythm, melody, and emotions of music, forming a unique artistic expression. This form of expression can be grand and spectacular, as well as delicate and delicate, bringing different artistic enjoyment to the audience.",
            'In order to meet the needs of different customers, Music and Dance Fountain provides customized services. Customers can choose different fountain designs, music tracks, lighting effects, etc. according to their preferences and needs. This personalized service makes each music and dance fountain unique, allowing for better integration into specific environments and scenes.'
        ],
        img: [
            'img/bronze/music-fountain-1.jpg',
            'img/bronze/music-fountain-2.jpg',
            'img/bronze/music-fountain-3.jpg',
            'img/bronze/music-fountain-4.jpg',
        ]
    },
    {   
        id: 18,
        name:'Marble carving kneeling praying angel statue',
        title: 'Marble angel Statue',
        num: 'MRED-011',
        Material: 'Marble',
        type: 'Marble angel statue',
        size: 'Life size or as requested',
        price: 'USD 700-3800 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: ' Fountain Construction',
        introduction: [
            "This is the marble carving kneeling praying angel statueIn the sculpture of a pair of angels kneeling and praying, both angels present devout postures. Their bodies lean forward, their heads lowered, and their hands crossed on their chests, showing piety and reverence towards God. ",
            "One of the angels crossed their hands, further emphasizing his devout and praying attitude. Their facial expressions are calm and gentle, conveying inner peace and reverence for God.",
            "Angel sculptures are often endowed with the meaning of protection and blessings. In this sculpture of angels kneeling and praying, the angels bow their heads and pray devoutly, representing love and protection for humanity. Their posture and expressions convey reverence and piety towards God, as well as care and blessings for humanity. This type of sculpture is often used to express admiration and faith in angels, and is also a way to pray for their protection and blessings.",
            'Angel sculpture has a wide range of applications in real life. Firstly, they are often used in churches, temples, and other religious places as objects of worship and admiration for believers during religious activities and rituals, enhancing the religious atmosphere and inspiring devout faith.'
        ],
        img: [
            'img/bronze/marble-angel-1.jpg',
            'img/bronze/marble-angel-2.jpg',
            'img/bronze/marble-angel-3.jpg',
            'img/bronze/marble-angel-4.jpg',
        ]
    },
    {   
        id: 19,
        name:'Bronze Lion Statues Outdoor',
        title: 'Bronze Lion Statue',
        num: 'MRED-019',
        Material: 'Bronze/ Brass/ Copper',
        type: 'bronze lion statue',
        size: 'Life size or as requested',
        price: 'USD 790-3990 per piece',
        Payment: 'T/T, PayPal, Western Union or other ways',
        delivery: ' period: 15-35days',
        PackageIn: 'soft plastic foam/ blanket',
        PackageOut: 'Strong wooden package',
        Categories: ' Fountain Construction',
        introduction: [
            "This is a pair of bronze lion statues. Their image is lying flat, with one mouth slightly open, seeming to make a majestic roar, while the other has a tightly closed mouth and a forward tail, giving the overall appearance both majestic and leisurely. This posture not only showcases the strength and dignity of a lion, but also reveals a approachable affinity. ",
            "The production process of Bronze HSBC Lion Statue usually includes multiple steps such as model making, wax casting, lost wax casting, and polishing. Firstly, artists will create clay sculpture prototypes based on design drawings or clay models; Next, using the lost wax technique, the wax replicated model is wrapped in refractory material and heated to melt off the wax, forming a cavity, and then injected with melted bronze liquid; After cooling and solidifying, the external material is removed to obtain the initial prototype of the bronze sculpture. Subsequently, it needs to undergo fine polishing and coloring treatment to finally present the delicate texture we see.",
            "Xintuo Sculpture Company is committed to providing customers with high-quality sculpture works, including various lion sculptures. Whether you prefer traditional style or modern design, we have ready-made products for you to choose from. At the same time, we also provide customized services to design and produce unique lion sculptures according to your specific requirements, ensuring that every detail meets your expectations.",
            'Angel sculpture has a wide range of applications in real life. Firstly, they are often used in churches, temples, and other religious places as objects of worship and admiration for believers during religious activities and rituals, enhancing the religious atmosphere and inspiring devout faith.'
        ],
        img: [
            'img/bronze/bronze-lion-1.jpg',
            'img/bronze/bronze-lion-2.jpg',
            'img/bronze/bronze-lion-3.jpg',
            'img/bronze/bronze-lion-4.jpg',
        ]
    },
]
